Can run scenario 1 [skip ci]

diff --git a/test_scripts/scenario1_2 b/test_scripts/scenario1_2
--- a/test_scripts/scenario1_2
+++ b/test_scripts/scenario1_2
@@ -260,7 +260,7 @@ then
   exit 1
 fi
 
-xdotool windowactivate $id sleep 0.1 key Escape sleep 0.2
+xdotool windowactivate $id sleep 0.4 key Escape sleep 0.4
 
 ####################################
 # 'Mijn persoonlijke werktheorie, programma voor de student'
@@ -273,7 +273,7 @@ then
   exit 1
 fi
 
-xdotool windowactivate $id sleep 0.1 key Escape sleep 0.2
+xdotool windowactivate $id sleep 0.8 key Escape sleep 0.8
 
 ####################################
 # 'Mijn persoonlijke werktheorie, programma voor de student'
@@ -286,4 +286,18 @@ then
   exit 1
 fi
 
-xdotool windowactivate $id sleep 0.1 key Escape sleep 0.2
+xdotool windowactivate $id sleep 0.8 key Escape sleep 0.8
+
+####################################
+# 'Mijn persoonlijke werktheorie, programma voor de student'
+# Close
+####################################
+id=`get_dialog_id "Mijn persoonlijke werktheorie, programma voor de student"`
+if [ -z $id ]
+then
+  echo "ID not found, line "$LINENO
+  exit 1
+fi
+
+xdotool windowactivate $id sleep 0.8 key Escape sleep 0.8
+
